"""Add category to tickets

Revision ID: cf352e1ae6f5
Revises: 13e1362804db
Create Date: 2025-06-29 13:46:01.434312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf352e1ae6f5'
down_revision: Union[str, Sequence[str], None] = '13e1362804db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'category')
    # ### end Alembic commands ###
